List

In [5]:
numbers = [10, 20, 30, 40, 50, 60, 70]
print("Original List:", numbers)
#Basic Slicing
print("numbers[1:4]   =>", numbers[1:4])     
print("numbers[:3]    =>", numbers[:3])      
print("numbers[3:]    =>", numbers[3:])      
print("numbers[:]     =>", numbers[:])       
#Slicing with Step
print("numbers[::2]   =>", numbers[::2])     
print("numbers[1::2]  =>", numbers[1::2])    
#Negative Indices
print("numbers[-3:]   =>", numbers[-3:])     
print("numbers[:-2]   =>", numbers[:-2])     
#Reverse the List
print("numbers[::-1]  =>", numbers[::-1])    

#list comprehension
squares = [x**2 for x in range(1, 6)]
print("Squares:", squares)

even = [number for number in numbers if number % 2 == 0]
print("Even Numbers:", even)

even = [number for number in numbers if number % 2 != 0]
print("Odd Numbers:", even)

#operations in list 
print("Original list:", numbers)
# Access elements
print("First element:", numbers[0])
print("Last element:", numbers[-1])
# Modify an element
numbers[2] = 35
print("Modifying index 2 (30 to 35):", numbers)
# Add elements
numbers.append(80)
print("After append(80):", numbers)
numbers.insert(1, 15)
print("After insert(15) at index 1:", numbers)
# Remove elements
numbers.remove(35)
print("After remove(35):", numbers)
popped_value = numbers.pop()
print("After pop():", numbers)
print("Popped value:", popped_value)
del numbers[2]
print("After del numbers[2]:", numbers)
# Check existence
print("Is 40 in numbers?", 40 in numbers)
print("Is 99 in numbers?", 99 in numbers)
# Length of list
print("Length of list:", len(numbers))
# Loop through list
print("Looping through list:")
for num in numbers:
    print(num, end=" ")
print()
# Sort and reverse
numbers.sort()
print("Sorted list (ascending):", numbers)
numbers.sort(reverse=True)
print("Sorted list (descending):", numbers)
numbers.reverse()
print("List after reverse():", numbers)
# Copy list
copied_list = numbers.copy()
print("Copied list:", copied_list)
# Concatenate with another list
extra = [100, 110]
combined = numbers + extra
print("Concatenated list:", combined)
# Clear list
numbers.clear()
print("After clear():", numbers)

Original List: [10, 20, 30, 40, 50, 60, 70]
numbers[1:4]   => [20, 30, 40]
numbers[:3]    => [10, 20, 30]
numbers[3:]    => [40, 50, 60, 70]
numbers[:]     => [10, 20, 30, 40, 50, 60, 70]
numbers[::2]   => [10, 30, 50, 70]
numbers[1::2]  => [20, 40, 60]
numbers[-3:]   => [50, 60, 70]
numbers[:-2]   => [10, 20, 30, 40, 50]
numbers[::-1]  => [70, 60, 50, 40, 30, 20, 10]
Squares: [1, 4, 9, 16, 25]
Even Numbers: [10, 20, 30, 40, 50, 60, 70]
Odd Numbers: []
Original list: [10, 20, 30, 40, 50, 60, 70]
First element: 10
Last element: 70
Modifying index 2 (30 to 35): [10, 20, 35, 40, 50, 60, 70]
After append(80): [10, 20, 35, 40, 50, 60, 70, 80]
After insert(15) at index 1: [10, 15, 20, 35, 40, 50, 60, 70, 80]
After remove(35): [10, 15, 20, 40, 50, 60, 70, 80]
After pop(): [10, 15, 20, 40, 50, 60, 70]
Popped value: 80
After del numbers[2]: [10, 15, 40, 50, 60, 70]
Is 40 in numbers? True
Is 99 in numbers? False
Length of list: 6
Looping through list:
10 15 40 50 60 70
Sorted list (ascending): [10, 15, 40, 50, 60, 70]
Sorted list (descending): [70, 60, 50, 40, 15, 10]
List after reverse(): [10, 15, 40, 50, 60, 70]
Copied list: [10, 15, 40, 50, 60, 70]
Concatenated list: [10, 15, 40, 50, 60, 70, 100, 110]
After clear(): []

In [ ]:
#Tuples

In [6]:
# Creating tuples
mytuple = ("apple", "banana", "cherry")
thistuple = ("apple", "banana", "cherry")
print(thistuple)

# Accessing tuple element by index
thistuple = ("apple", "banana", "cherry")
print(thistuple[1])

# Accessing last element using negative index
thistuple = ("apple", "banana", "cherry")
print(thistuple[-1])

# Slicing the tuple
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:5])  # From index 2 to 4

# Slicing from beginning to index 4 (excluded)
print(thistuple[:4]) 

# Slicing from index 2 to end
print(thistuple[2:])  

# Membership test
thistuple = ("apple", "banana", "cherry")
if "apple" in thistuple:
    print("Yes, 'apple' is in the fruits tuple")

# Modifying tuple by converting to list
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)
print(x)

# Adding element by tuple concatenation
thistuple = ("apple", "banana", "cherry")
y = ("orange",)
thistuple += y
print(thistuple)

# Appending item by converting to list
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.append("orange")
thistuple = tuple(y)
print(thistuple)

# Removing item by converting to list
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.remove("apple")
thistuple = tuple(y)
print(thistuple)

# Iterating through a tuple
thistuple = ("apple", "banana", "cherry")
for x in thistuple:
    print(x)

# Tuple concatenation
tuple1 = ("a", "b", "c")
tuple2 = (1, 2, 3)
tuple3 = tuple1 + tuple2
print(tuple3)

# Tuple repetition
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2
print(mytuple)

('apple', 'banana', 'cherry')
banana
cherry
('cherry', 'orange', 'kiwi')
('apple', 'banana', 'cherry', 'orange')
('cherry', 'orange', 'kiwi', 'melon', 'mango')
Yes, 'apple' is in the fruits tuple
('apple', 'kiwi', 'cherry')
('apple', 'banana', 'cherry', 'orange')
('apple', 'banana', 'cherry', 'orange')
('banana', 'cherry')
apple
banana
cherry
('a', 'b', 'c', 1, 2, 3)
('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')

Sets

In [9]:
# Creating a set
fruits = {"apple", "banana", "cherry"}
print("Original set:", fruits)
# Adding elements to a set
fruits.add("orange")
print("After adding orange:", fruits)
# Adding multiple elements using update()
fruits.update(["mango", "grape"])
print("After updating with mango and grape:", fruits)

# Removing elements
fruits.remove("banana")  
print("After removing banana:", fruits)

# Discarding elements 
fruits.discard("kiwi")  
print("After discarding kiwi:", fruits)

# Copying a set
copied_fruits = fruits.copy()
print("Copied set:", copied_fruits)

# Clearing all elements
copied_fruits.clear()
print("After clearing copied set:", copied_fruits)

# FROZENSET (immutable set)
frozen = frozenset(["apple", "banana", "cherry"])
print("Frozenset:", frozen)


# UNION, INTERSECTION, DIFFERENCE

setA = {"apple", "banana", "cherry"}
setB = {"cherry", "kiwi", "mango"}

# Union 
union_set = setA.union(setB)
print("Union:", union_set)

# Intersection 
intersection_set = setA.intersection(setB)
print("Intersection:", intersection_set)

# Difference 
difference_set = setA.difference(setB)
print("Difference (A - B):", difference_set)

Original set: {'apple', 'cherry', 'banana'}
After adding orange: {'apple', 'cherry', 'banana', 'orange'}
After updating with mango and grape: {'orange', 'cherry', 'banana', 'grape', 'apple', 'mango'}
After removing banana: {'orange', 'cherry', 'grape', 'apple', 'mango'}
After discarding kiwi: {'orange', 'cherry', 'grape', 'apple', 'mango'}
Copied set: {'cherry', 'grape', 'apple', 'mango', 'orange'}
After clearing copied set: set()
Frozenset: frozenset({'apple', 'cherry', 'banana'})
Union: {'cherry', 'banana', 'kiwi', 'apple', 'mango'}
Intersection: {'cherry'}
Difference (A - B): {'apple', 'banana'}

Dictionary

In [11]:
# Creating a simple dictionary
person = {
    "name": "Hanzla",
    "age": 24,
    "city": "Lahore"
}
# Accessing values
print("Name:", person["name"])
print("Age:", person["age"])
print("City:", person["city"])
# Adding a new key-value pair
person["email"] = "hanzla@gmail.com"
print("After adding email:", person)
# Updating an existing value
person["age"] = 26
print("After updating age:", person)
# Removing a key-value pair
person.pop("city")
print("After removing city:", person)

# NESTED DICTIONARY
students = {
    "student1": {
        "name": "Hanzla",
        "age": 24,
        "grades": [85, 90, 78]
    },
    "student2": {
        "name": "Ahmad",
        "age": 22,
        "grades": [88, 76, 92]
    },
    "student3": {
        "name": "Salman",
        "age": 21,
        "grades": [90, 91, 89]
    }
}

# Accessing nested dictionary values
print("Student1's name:", students["student1"]["name"])
print("Student2's grades:", students["student2"]["grades"])
# Updating a nested value
students["student3"]["age"] = 23
print("Updated student3 age:", students["student3"]["age"])
# Adding a new student
students["student4"] = {
    "name": "Diana",
    "age": 19,
    "grades": [95, 87, 93]
}
print("After adding student4:", students)
# Looping through nested dictionary
print("\n-- Student Details --")
for key, info in students.items():
    print(f"{key}: {info['name']}, Age: {info['age']}, Grades: {info['grades']}")
# pop() vs popitem()
# Using pop() remove item by key
removed_student = students.pop("student2")
print("\nRemoved using pop('student2'):", removed_student)
print("Remaining students:", students)

# Using popitem() - removes last item (LIFO order)
last_item = students.popitem()
print("\nRemoved using popitem():", last_item)
print("Remaining students after popitem():", students)

Name: Hanzla
Age: 24
City: Lahore
After adding email: {'name': 'Hanzla', 'age': 24, 'city': 'Lahore', 'email': 'hanzla@gmail.com'}
After updating age: {'name': 'Hanzla', 'age': 26, 'city': 'Lahore', 'email': 'hanzla@gmail.com'}
After removing city: {'name': 'Hanzla', 'age': 26, 'email': 'hanzla@gmail.com'}
Student1's name: Hanzla
Student2's grades: [88, 76, 92]
Updated student3 age: 23
After adding student4: {'student1': {'name': 'Hanzla', 'age': 24, 'grades': [85, 90, 78]}, 'student2': {'name': 'Ahmad', 'age': 22, 'grades': [88, 76, 92]}, 'student3': {'name': 'Salman', 'age': 23, 'grades': [90, 91, 89]}, 'student4': {'name': 'Diana', 'age': 19, 'grades': [95, 87, 93]}}

-- Student Details --
student1: Hanzla, Age: 24, Grades: [85, 90, 78]
student2: Ahmad, Age: 22, Grades: [88, 76, 92]
student3: Salman, Age: 23, Grades: [90, 91, 89]
student4: Diana, Age: 19, Grades: [95, 87, 93]

Removed using pop('student2'): {'name': 'Ahmad', 'age': 22, 'grades': [88, 76, 92]}
Remaining students: {'student1': {'name': 'Hanzla', 'age': 24, 'grades': [85, 90, 78]}, 'student3': {'name': 'Salman', 'age': 23, 'grades': [90, 91, 89]}, 'student4': {'name': 'Diana', 'age': 19, 'grades': [95, 87, 93]}}

Removed using popitem(): ('student4', {'name': 'Diana', 'age': 19, 'grades': [95, 87, 93]})
Remaining students after popitem(): {'student1': {'name': 'Hanzla', 'age': 24, 'grades': [85, 90, 78]}, 'student3': {'name': 'Salman', 'age': 23, 'grades': [90, 91, 89]}}